name: volume_flash_plugin
description: "A Flutter package that provides easy controls for adjusting volume and toggling the flashlight on both Android and iOS devices. Ideal for creating multimedia applications."
repository: "https://github.com/shahzaibNiazi/volume_flash_plugin/tree/master"
version: 0.0.4


environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.example.volume_flash_plugin
        pluginClass: VolumeFlashPlugin
      ios:
        pluginClass: VolumeFlashPlugin

