name: volume_flash_plugin
description: "A Flutter package that provides easy controls for adjusting volume and toggling the flashlight on both Android and iOS devices. Ideal for creating multimedia applications."
repository: "https://github.com/shahzaibNiazi/volume_flash_plugin/tree/master"
version: 0.0.1


environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.example.volume_flash_plugin
        pluginClass: VolumeFlashPlugin
      ios:
        pluginClass: VolumeFlashPlugin


  uses-material-design: true

